name: flutter_kirthan
description: Kirthan project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.0.1
  flutter_form_builder: ^3.8.1
  http: ^0.12.0
  shared_preferences: 0.5.7+1
  google_sign_in: ^4.4.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  flutter_facebook_login: ^3.0.0
  flutter_auth_buttons: ^0.8.0
  provider: ^4.0.5+1
  screen: ^0.0.5
  table_calendar:
  google_fonts: ^1.0.0
  rating_dialog: ^1.0.0
  firebase_messaging : ^6.0.16
  flutter_local_notifications: ^1.4.4+2
  google_maps_flutter: ^0.5.11
  location: ^2.3.5
  flutter_google_places: ^0.1.4
  geolocator: 5.0.1
  geocoder:
  geolocation:
  autocomplete_textfield:
  flutter_polyline_points:
  flutter_spinkit:
  dio:
  equatable: ^0.2.6
  great_circle_distance:
  flutter_bloc: ^4.0.0
  bloc:
  image_picker: ^0.5.3+1
  firebase_storage:
  flutter_svg:
  get_it: ^4.0.1
  flutter_icons: ^1.0.0+1
  firebase_helpers:
  cloud_firestore:





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/default_icon.png
  fonts:
    - family: Distant Galaxy
      fonts:
        - asset: assets/fonts/DISTGRG_.ttf
